### ISSUE TITLE
Not connecting to Discord anymore.

### ISSUE THREAD

**Issue by Phate6660** [JakeStanger/mpd-discord-rpc#14]
Oddly enough, there are no errors or anything. It runs just like it usually does.

However, there is simply just no rich presence being displayed.

I'm not sure what the issue could be, as my own plus other rich presence programs work fine.

Though it did stop working after Discord updated, so that could be part of the issue.

**Comment by JakeStanger** [comment]
Hm, I'm up to date (updated this evening) and it's working fine for me. Are you using Discord stable or Canary? I take it `mpd-discord-rpc` isn't producing any errors?

**Comment by Phate6660** [comment]
Hmm, found the problem.

For some reason, it can't connect to Discord when ran from `tmux`.

Which is odd because it worked perfectly fine that way before.

**Comment by JakeStanger** [comment]
That is *very* odd. I wonder if other RPC programs have that same issue. I can't see why tmux would get in the way of a socket connection?

**Comment by Phate6660** [comment]
Nope, I'm not using any plugins.

My music setup has always been done through `tmux` and there were never any issues before.

I'm not sure what could have changed to cause that outcome unless maybe a `tmux` update or discord update broke it.

**Comment by Phate6660** [comment]
And I forgot to mention there are no errors.

mpd-discord-rpc even acts like it did in fact connect and is running fine.

**Comment by JakeStanger** [comment]
Just installed `tmux` on Arch and tried running it from there, and it's definitely still working for me.

An oddity, and something to keep my eyes on I guess. It sounds like it's *probably* not a bug with my code at least.


> mpd-discord-rpc even acts like it did in fact connect and is running fine.

I suspected this'd be the case. The rpc connection is a bit crap and just sorta silently falls over if it can't connect. I need to have a poke at it when I get time and see if I can improve that...

**Comment by Phate6660** [comment]
Just wanted to comment and say that it's working through tmux now.
I'm not sure what the issue was, I never changed anything, it just started working again.

**Comment by JakeStanger** [comment]
Thanks for letting me know, glad it's resolved.

An odd one...
