### ISSUE TITLE
Default fallback if missing from config 

### ISSUE THREAD

**Issue by Kranzes** [JakeStanger/mpd-discord-rpc#18]
It would be nice if the program would fallback to the default options if they aren't defined in the `config.toml`.

For example, a `config.toml` with this content:
```toml
[format]
large_image = ""
```
Should still work, and not crash the program. The program will then use the default options but replace the large_image option with the one defined in the config file.

**Comment by JakeStanger** [comment]
This should already be the case, my bad for not spotting that in the PR that added those new options.

I will try and get that fixed tonight.

**Comment by Kranzes** [comment]
It is not the case only for the new options, the program crashes when just specifying:
```toml
 [format]
 details = "$title"
   ```

**Comment by JakeStanger** [comment]
Right yeah, because those ones were guaranteed to exist in a config unless removed. Will sort those ones too 👍

**Comment by Kranzes** [comment]
Don't forget the stuff outside of `[format]` too.

**Comment by OliverKovacs** [comment]
@JakeStanger I could take a look at this.

Maybe ditch the system with defaults.rs and make a default config toml and then merge its values to the values loaded from the user's config?

**Comment by JakeStanger** [comment]
Yeah that'd be great! You could probably keep the defaults struct and just do a better job of merging that into the config struct, but if you think there's a better way go ahead and I'll have a review.
