### ISSUE TITLE
Use the merge crate

### ISSUE THREAD

**Issue by OliverKovacs** [JakeStanger/mpd-discord-rpc#21]
Use the [merge](https://docs.rs/merge/latest/merge/) crate instead of `Config.merge()` and `Format.merge()`.
This would simplify the code and make adding new options easier by introducing a new dependency.
I could implement this if i get the green light.

**Comment by JakeStanger** [comment]
Yeah I like the look of that crate , that'd definitely be cleaner. Go for it :)
