### ISSUE TITLE
Question how to set the image

### ISSUE THREAD

**Issue by seniorkiller** [JakeStanger/mpd-discord-rpc#23]
so reading through the readme file i cant find anything related to changing the image that shown in the discord other than removing it. so how does it work? is it harcoded to  only show it or hide it or you can set it to whatever you want? what i wanted is to use from the music file it self(file thumbnail or something not sure what it called) but not sure how.

it will be nice if theres some other description relate to it in the documentation.

**Comment by JakeStanger** [comment]
Discord doesn't offer a lot of control over images unfortunately, but basically:

- Named image assets are uploaded in the app registration in at <https://discord.com/developers/>
- The code references these assets by name (the default for both the small and large image is `notes`, which can be changed in the config file)
- Discord automatically finds the `notes` image for the app and shows that in the client

By creating your own app registration, uploading your own assets and then updating the config with your own app id and small/large asset names you can set a custom static image. You won't be able to do anything dynamic like setting it to the current album art though as Discord simply doesn't support it I'm afraid.

**Comment by seniorkiller** [comment]
Thanks for answering, anyway should i close this issue? 
Im done with my question but it might be useful to others

**Comment by JakeStanger** [comment]
Yeah I'll close this now, the thread will remain here in case anybody else does have the same question.
