### ISSUE TITLE
feature request: album cover

### ISSUE THREAD

**Issue by Kranzes** [JakeStanger/mpd-discord-rpc#25]
It would be great if there was an option to have it fetch the appropriate album cover image from the internet and show it in the image box. Many Discord RPCs for music already do that.

**Comment by JakeStanger** [comment]
Hey, do you have any examples of other RPC clients that do that? I'd be willing to pick them apart and see if I can do what they're doing if they are. It's something I'd love to be able to implement, but I'm yet to find a way to do it. 

As far as I've been able to tell, you'd need to require a separate application per user, and you'd have to have a whole OAuth system to auth with discord's dev portal, and constantly add/remove assets to the app registration.

**Comment by Kranzes** [comment]
<https://github.com/NextFire/apple-music-discord-rpc>
<https://github.com/wxllow/applemusicrp>

**Comment by JakeStanger** [comment]
Interesting, thanks! From a quick glance it looks like you can pass the image file contents itself, which I had absolutely no idea about. 

I'll have a crack at this later and see what I can do.

**Comment by JakeStanger** [comment]
Done! And if you add MusicBrainz tags to your tracks (using Picard or similar) it should be super fast/reliable.
