### ISSUE TITLE
InvalidMessage when playing a song

### ISSUE THREAD

**Issue by Allavaz** [JakeStanger/mpd-discord-rpc#39]
Hi, I installed this with cargo, and when I run it it seems to work fine until I play a song, I get a InvalidMessage error:

![image](https://github.com/JakeStanger/mpd-discord-rpc/assets/8140592/b281c6b4-e12f-465d-b711-4ac54fcc3a3f)

I'm on macOS Monterey if it's any help. Let me know if you need any extra info.

**Comment by JakeStanger** [comment]
Hey, it looks like that's an issue with the [MPD Client library](https://github.com/elomatreb/mpd_client) based on the errors. That may be doing something Linux-specific, causing a problem with the connection on macOS.

If you open an issue there, you can reference this one and I'll keep an eye on it and update the library here when I can.

**Comment by Allavaz** [comment]
Turns out it was actually a bug in MPD itself, it was sending invalid UTF-8 when I `telnet`'d into it and asked for the current song, so `mpd_client` couldn't handle it. I installed the master branch version of MPD and now it works fine. Also `mpd-discord-rpc` is working fine now. Thanks for the help!
