### ISSUE TITLE
elapsed time does not update

### ISSUE THREAD

**Issue by Kranzes** [JakeStanger/mpd-discord-rpc#6]
so apparently the elapsed time on discord updates every 2 seconds for the person thats running ``mpd-discord-rpc``, but it does not update for the other person that is just viewing the other person's discord status/profile.
it only updates once every minute or so, it inst consistent at all.
i would like if you could make so it updates the elapsed time every 1 second for both of the users, the one that is running ``mpd-discord-rpc`` and the one that is viewing the other person's profile.

**Comment by JakeStanger** [comment]
Hey, sorry it took me so long to get to this but I somehow completely missed the issue.

I think that's a limitation of how Discord's RPC system works, which is a bugger. I might be able to use the time elapsed system that's built in but it does limit the formatting annoyingly.

**Comment by JakeStanger** [comment]
I think that's the best I can do. How does that work for you?

**Comment by Phate6660** [comment]
I love this. Not OP, just wanted to thank you for adding this.

**Comment by JakeStanger** [comment]
I think I'm pretty happy with it. I'm going to merge the PR and release an update tomorrow evening.

**Comment by JakeStanger** [comment]
Closed for now. @Kranzes if this doesn't solve your problem, feel free to re-open.
